#
# Blog Settings
#
author: Alex Wang
description: Alex tech blog
url: http://www.alexcoding.me
title: Alex Blog
subtitle: ...and you like it
gravatar_url: ''
subscribe_rss: http://www.alexcoding.me/feed.xml

# Github repositories
github_user: foxlog
github_repo_url: https://github.com/foxlog/alexcode/

# Twitter
twitter_user: foxlog
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: alexcoding
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: ''


#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories
highlighter: pygments

gems:
  - jekyll-redirect-from
  - jekyll-sitemap